- Samples/Sample XML/EducationOrganization.xml
- Samples/Sample XML/IndicatorDescriptor.xml
- Samples/Sample XML/IndicatorGroupDescriptor.xml
- Samples/Sample XML/IndicatorLevelDescriptor.xml
- Schemas/Bulk/Ed-Fi-Core.xsd
- Schemas/Bulk/Interchange-Descriptors.xsd
- Schemas/Bulk/SchemaAnnotation.xsd
- [DATASTD-1464] added EducationOrganizationIndicator to EducationOrganization
- [DATASTD-1464] sample data for EducationOrganizationIndicator and descriptors
> [DATASTD-1464] added EducationOrganizationIndicator to EducationOrganization

- Schemas/Bulk/Ed-Fi-Core.xsd
[DATASTD-1464] update EducationOrganizationIndicator Period to be an optional collection
> [DATASTD-1464] update EducationOrganizationIndicator Period to be an optional collection

- Samples/Sample XML/EducationOrganization.xml
- Schemas/Bulk/Ed-Fi-Core.xsd
[DATASTD-1464] added Period to EducationOrganizationIndicator sample data
> [DATASTD-1464] added Period to EducationOrganizationIndicator sample data

- Samples/Sample XML/EducationOrganization.xml
[DATASTD-1461] created sample data for CommunityOrganization, CommunityProvider, and CommuityProviderLicense
> [DATASTD-1461] created sample data for CommunityOrganization, CommunityProvider, and CommuityProviderLicense

- Samples/Sample XML/StudentDiscipline.xml
[DATASTD-1393] updated behavior descriptor reference
> [DATASTD-1393] updated behavior descriptor reference

- Samples/Sample XML/StudentProgram.xml
Updated 20 student records to include disabilities.
> Update StudentProgram to add Students with disability

- Samples/Sample XML/StudentProgram.xml
Added sample data for StudentSchoolFoodServiceProgramAssociationSchoolFoodServiceProgramService (Free Lunch, Reduced Price Lunch, Free Breakfast, Reduced Price Breakfast)
> Added sample data for SchoolFoodServiceProgramService

- Descriptors/AssessmentIdentificationSystemDescriptor.xml
Fixed formatting issue with the added descriptor value National in AssessmentIdentificationSystemDescriptor
> [DATASTD-1392] Fixed formatting issue

- Descriptors/PostSecondaryInstitutionLevelDescriptor.xml
[DATASTD-1486] Updated PostSecondaryInstitutionLevelDescriptor to align with Carnegie values
> [DATASTD-1486] Updated PostSecondaryInstitutionLevelDescriptor

- Descriptors/CreditCategoryDescriptor.xml
[DATASTD-1635] Fixed formatting issue with CreditCategoryDescriptor file
> [DATASTD-1635] Fixed formatting issue with CreditCategoryDescriptor file

- Descriptors/AccommodationDescriptor.xml
- Descriptors/GradeLevelDescriptor.xml
- Descriptors/SchoolCategoryDescriptor.xml
- Descriptors/SchoolTypeDescriptor.xml
- Descriptors/StaffClassificationDescriptor.xml
[DATASTD-1671] Updated values on some descriptor files including AccomodationDescriptor, SchoolCategoryDescriptor, StaffClassificationDescriptor, SchoolTypeDescriptor, and GradeLevelDescriptor.
> [DATASTD-1671] Updated values on some descriptor files 

- Descriptors/TribalAffiliationDescriptor.xml
[DATASTD-1622] Aligned TribalAffilitionDescriptor values with Federally-defined values
> [DATASTD-1622] Aligned TribalAffilitionDescriptor values with Federal

- Samples/Sample XML/StudentGradebook.xml
[DATASTD-1735] Added SubmissionStatus and AssignmentLateStatus sample data to StudentGradebook
> [DATASTD-1735] Added SubmissionStatus and AssignmentLateStatus data

- Samples/Sample XML/StudentGradebook.xml
[DATASTD-1765] Updated sample data by changing GradebookEntryTitle to Title
> [DATASTD-1765] Updated sample data by changing GradebookEntryTitle

- Samples/Sample XML/AssessmentMetadata-StateAssessment.xml
- Samples/Sample XML/StudentAssessment-LearningStandardsMastery.xml
- Samples/Sample XML/StudentAssessment-SAT.xml
- Samples/Sample XML/StudentAssessment-StateAssessment.xml
[DATASTD-1826] Update AssessmentMetadata-StateAssessment.xml
[DATASTD-1826] Update StudentAssessment-LearningStandardsMastery.xml
[DATASTD-1826] Update StudentAssessment-StateAssessment.xml
[DATASTD-1826] Update StudentAssessment-SAT.xml
> [DATASTD-1826] Update assessment xml files

- Samples/Sample XML/StudentGradebook.xml
- Schemas/Bulk/Ed-Fi-Core.xsd
Changed SourceSystemNamespace to Namespace
> [DATASTD-1832] Updated StudentGradebook.xml and Ed-Fi-Core.xsd

- Descriptors/AssessmentPeriodDescriptor.xml
- Samples/Sample XML/StudentAssessment-ACT.xml
- Samples/Sample XML/StudentAssessment-LearningStandardsMastery.xml
- Samples/Sample XML/StudentAssessment-SAT.xml
- Samples/Sample XML/StudentAssessment-StateAssessment.xml
- Schemas/Bulk/Ed-Fi-Core.xsd
- Schemas/Bulk/Interchange-Descriptors.xsd
- Schemas/Bulk/SchemaAnnotation.xsd
XSD files were auto-generated from metaed build on branch DS-4.0-ME-3.x
> [DATASTD-1831] Update StudentAssessment-ACT.xml and xsd files

- Samples/Sample XML/StudentGradebook.xml
Changed SectionIdentifier to SourceSectionIdentifier
> [DATASTD-1839] Update StudentGradebook.xml

- Samples/Sample XML/Finance.xml
Fix AccountTypeDescriptor values
> [DATASTD-1889] Bug fix Finance.xml

- Samples/Sample XML/ObjectiveAssessmentSample.xml
- Samples/Sample XML/StudentAssessmentSample.xml
* [DATASTD-1889] Fix AssessmentReportingMethodDescriptor value
* [DATASTD-1889] Fix AssessmentSample.xml
[DATASTD-1889] Fix StudentAssessmentSample and ObjectiveAssessmentSample
> [DATASTD-1889] Fix StudentAssessmentSample and ObjectiveAssessmentSample

- Descriptors/DiagnosisDescriptor.xml
- Samples/Sample XML/StudentIntervention.xml
Updated DiagnosisDescriptor values and  updated sample files
> [DATASTD-1489] Update DiagnosisDescriptor values

- .github/workflows/Trigger EdFi.Ods.DB.Templates workflow in ODS repo.yml
triggered-from-datastandard-repo in the ODS repo will be triggered only after merge of this PR
> ODS-5564 Trigger EdFi.Ods.DB.Templates workflow in ODS repo workflow added

- Samples/Sample XML/MasterSchedule.xml
> [DATASTD-2107] Update MasterSchedule.xml

- Descriptors/CrisisTypeDescriptor.xml
- Descriptors/DisplacedStudentStatusDescriptor.xml
- Schemas/Bulk/Ed-Fi-Core.xsd
- Schemas/Bulk/Interchange-Descriptors.xsd
- Schemas/Bulk/SchemaAnnotation.xsd
https://tracker.ed-fi.org/browse/DATASTD-2165
> Create Crisis Event Entity

- Descriptors/TransportationPublicExpenseEligibilityDescriptor.xml
- Descriptors/TransportationTypeDescriptor.xml
- Descriptors/TravelDayofWeekDescriptor.xml
- Descriptors/TravelDirectionDescriptor.xml
- Schemas/Bulk/Ed-Fi-Core.xsd
- Schemas/Bulk/Interchange-Descriptors.xsd
- Schemas/Bulk/Interchange-StudentEnrollment.xsd
- Schemas/Bulk/SchemaAnnotation.xsd
https://tracker.ed-fi.org/browse/DATASTD-2182
> Descriptors

- Descriptors/Section504DisabilityTypeDescriptor.xml
- Schemas/Bulk/Ed-Fi-Core.xsd
- Schemas/Bulk/Interchange-Descriptors.xsd
- Schemas/Bulk/SchemaAnnotation.xsd
https://edfi.atlassian.net/browse/DATASTD-2299
> DATASTD-2299

- Samples/Sample XML/StudentDiscipline.xml
- Schemas/Bulk/Ed-Fi-Core.xsd
Create Sample Data for Weapon in StudentDisciplineIncidentBehaviorAssociation
> [DATASTD-2333] Create Sample Data for Weapon in SDIBA

- Samples/Sample XML/AssessmentRegistration.xml
- Schemas/Bulk/Ed-Fi-Core.xsd
[DATASTD-2338] Add StudentEdOrgAssessmentAccommodation ref to StudentAssessmentRegistraion
[DATASTD-2338]: https://edfi.atlassian.net/browse/DATASTD-2338?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DATASTD-2338] Add StudentEdOrgAssessmentAccom ref to StudentAssessReg

- Descriptors/AttendanceEventCategoryDescriptor.xml
- Descriptors/CharterApprovalAgencyTypeDescriptor.xml
- Descriptors/CredentialTypeDescriptor.xml
- Descriptors/DiplomaTypeDescriptor.xml
https://edfi.atlassian.net/browse/DATASTD-2342
> DATASTD-2342
